// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ImportFileModal: typeof import('./src/components/improt-file/ImportFileModal.vue')['default']
    LayoutDisplayPane: typeof import('./src/components/layout-analyzer/LayoutDisplayPane.vue')['default']
    LayoutTreePane: typeof import('./src/components/layout-analyzer/LayoutTreePane.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NodeInfoPane: typeof import('./src/components/layout-analyzer/NodeInfoPane.vue')['default']
    PaneHeader: typeof import('./src/components/common/PaneHeader.vue')['default']
    SearchModal: typeof import('./src/components/search/SearchModal.vue')['default']
    SettingsModal: typeof import('./src/components/settings/SettingsModal.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
