// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImportFileModal: typeof import('./components/improt-file/ImportFileModal.vue')['default']
    LayoutDisplayPane: typeof import('./components/layout-analyzer/LayoutDisplayPane.vue')['default']
    LayoutTreePane: typeof import('./components/layout-analyzer/LayoutTreePane.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    NodeInfoPane: typeof import('./components/layout-analyzer/NodeInfoPane.vue')['default']
    PaneHeader: typeof import('./components/common/PaneHeader.vue')['default']
    SearchModal: typeof import('./components/search/SearchModal.vue')['default']
    SearchResultModal: typeof import('./components/search/SearchResultModal.vue')['default']
    SettingsModal: typeof import('./components/settings/SettingsModal.vue')['default']
  }
}
